-- 0012 added the product format columns (size label, trim, template pages,
-- sized-by-option, paper label) at the A5 booklet's defaults, but db:seed never
-- touches a catalogue that already has rows, and production's was copied, not
-- seeded. This brings an existing catalogue to src/db/seedCatalogue.ts:
--
--  * A6 memorial and thank-you cards and 50 × 200 mm bookmarks get their
--    formats — only while still at the defaults and with no templates, since a
--    template's layout is drawn on its product's trim.
--  * The memorial cards' blurb loses "wallet-sized", if it hasn't been edited.
--  * The memory board is added (a no-op if the slug already exists). Only to a
--    catalogue that has products already: on a fresh database db:seed creates
--    it, and a row here would make the seed think it had already run.
--  * Those four products get the seed's placeholder pricing, one axis at a
--    time and only where the product has no options on that axis yet, so
--    nothing set up in /admin is duplicated or overwritten.
--
-- None of this shows on the site by itself: a product is only sellable once it
-- has a published template (getSellableProducts).
UPDATE `products` SET `size_label` = 'A6', `trim_width_mm` = 105, `trim_height_mm` = 148, `template_pages` = 2 WHERE `slug` = 'memorial-cards' AND `size_label` = 'A5' AND `trim_width_mm` = 148 AND `trim_height_mm` = 210 AND `template_pages` = 3 AND NOT EXISTS (SELECT 1 FROM `templates` WHERE `templates`.`product_id` = `products`.`id`);--> statement-breakpoint
UPDATE `products` SET `size_label` = 'A6', `trim_width_mm` = 105, `trim_height_mm` = 148, `template_pages` = 2 WHERE `slug` = 'thank-you-cards' AND `size_label` = 'A5' AND `trim_width_mm` = 148 AND `trim_height_mm` = 210 AND `template_pages` = 3 AND NOT EXISTS (SELECT 1 FROM `templates` WHERE `templates`.`product_id` = `products`.`id`);--> statement-breakpoint
UPDATE `products` SET `size_label` = '50 × 200 mm', `trim_width_mm` = 50, `trim_height_mm` = 200, `template_pages` = 2 WHERE `slug` = 'bookmarks' AND `size_label` = 'A5' AND `trim_width_mm` = 148 AND `trim_height_mm` = 210 AND `template_pages` = 3 AND NOT EXISTS (SELECT 1 FROM `templates` WHERE `templates`.`product_id` = `products`.`id`);--> statement-breakpoint
UPDATE `products` SET `description` = 'A6 cards with their photo and dates on the front and a verse on the back, for family and friends to keep.' WHERE `slug` = 'memorial-cards' AND `description` = 'Wallet-sized cards with their photo and dates, for family and friends to keep.';--> statement-breakpoint
INSERT INTO `products` (`slug`, `label`, `description`, `occasion`, `size_label`, `trim_width_mm`, `trim_height_mm`, `template_pages`, `sized_by_option`, `paper_label`, `sort_order`, `is_active`) SELECT 'memory-board', 'Memory Board', 'A picture board of their life for the entrance or the wake, from A4 up to A0, mounted with an easel if you need one.', 'service', 'A4 to A0', 210, 297, 1, true, 'Finish', 3, true FROM DUAL WHERE EXISTS (SELECT 1 FROM (SELECT 1 FROM `products` LIMIT 1) `existing`) ON DUPLICATE KEY UPDATE `slug` = `slug`;--> statement-breakpoint
INSERT INTO `page_count_options` (`product_id`, `slug`, `label`, `page_count`, `base_rate_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`page_count`, `v`.`base_rate_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'both-sides' AS `slug`, 'Printed both sides' AS `label`, 2 AS `page_count`, 110 AS `base_rate_pence`, 'Full colour on the front and the back' AS `note`, 0 AS `sort_order`, true AS `is_active`) `v` WHERE `p`.`slug` = 'memorial-cards' AND NOT EXISTS (SELECT 1 FROM `page_count_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `paper_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'silk-card' AS `slug`, 'Silk card' AS `label`, '1.0000' AS `multiplier`, '350gsm silk card — sturdy, with a soft sheen' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'gloss-card', 'Gloss card', '1.0000', '350gsm gloss card — bright, high-contrast photographs', 1, true UNION ALL SELECT 'uncoated-card', 'Uncoated card', '1.0500', '350gsm uncoated card — natural, and easy to write on', 2, true) `v` WHERE `p`.`slug` = 'memorial-cards' AND NOT EXISTS (SELECT 1 FROM `paper_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `quantity_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `copies`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`copies`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT '10' AS `slug`, '10' AS `label`, '1.0000' AS `multiplier`, NULL AS `note`, 10 AS `copies`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT '25', '25', '0.9000', NULL, 25, 1, true UNION ALL SELECT '50', '50', '0.8000', NULL, 50, 2, true UNION ALL SELECT '75', '75', '0.7500', NULL, 75, 3, true UNION ALL SELECT '100', '100', '0.7000', NULL, 100, 4, true UNION ALL SELECT '150', '150', '0.6500', NULL, 150, 5, true UNION ALL SELECT '200', '200', '0.6000', NULL, 200, 6, true) `v` WHERE `p`.`slug` = 'memorial-cards' AND NOT EXISTS (SELECT 1 FROM `quantity_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `delivery_options` (`product_id`, `slug`, `label`, `price_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`price_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'standard' AS `slug`, 'Standard delivery' AS `label`, 0 AS `price_pence`, 'Free — 3 to 5 working days' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'next-day', 'Next day delivery', 1000, 'Order before 11am for next working day', 1, true) `v` WHERE `p`.`slug` = 'memorial-cards' AND NOT EXISTS (SELECT 1 FROM `delivery_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `page_count_options` (`product_id`, `slug`, `label`, `page_count`, `base_rate_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`page_count`, `v`.`base_rate_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'both-sides' AS `slug`, 'Printed both sides' AS `label`, 2 AS `page_count`, 120 AS `base_rate_pence`, 'Full colour on the front and the back' AS `note`, 0 AS `sort_order`, true AS `is_active`) `v` WHERE `p`.`slug` = 'bookmarks' AND NOT EXISTS (SELECT 1 FROM `page_count_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `paper_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'silk-card' AS `slug`, 'Silk card' AS `label`, '1.0000' AS `multiplier`, '350gsm silk card — sturdy, with a soft sheen' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'gloss-card', 'Gloss card', '1.0000', '350gsm gloss card — bright, high-contrast photographs', 1, true UNION ALL SELECT 'uncoated-card', 'Uncoated card', '1.0500', '350gsm uncoated card — natural, and easy to write on', 2, true UNION ALL SELECT 'laminated', 'Laminated silk card', '1.2500', '350gsm silk card, laminated both sides — wipe-clean and hard-wearing', 3, true) `v` WHERE `p`.`slug` = 'bookmarks' AND NOT EXISTS (SELECT 1 FROM `paper_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `quantity_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `copies`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`copies`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT '10' AS `slug`, '10' AS `label`, '1.0000' AS `multiplier`, NULL AS `note`, 10 AS `copies`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT '25', '25', '0.9000', NULL, 25, 1, true UNION ALL SELECT '50', '50', '0.8000', NULL, 50, 2, true UNION ALL SELECT '75', '75', '0.7500', NULL, 75, 3, true UNION ALL SELECT '100', '100', '0.7000', NULL, 100, 4, true UNION ALL SELECT '150', '150', '0.6500', NULL, 150, 5, true UNION ALL SELECT '200', '200', '0.6000', NULL, 200, 6, true) `v` WHERE `p`.`slug` = 'bookmarks' AND NOT EXISTS (SELECT 1 FROM `quantity_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `delivery_options` (`product_id`, `slug`, `label`, `price_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`price_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'standard' AS `slug`, 'Standard delivery' AS `label`, 0 AS `price_pence`, 'Free — 3 to 5 working days' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'next-day', 'Next day delivery', 1000, 'Order before 11am for next working day', 1, true) `v` WHERE `p`.`slug` = 'bookmarks' AND NOT EXISTS (SELECT 1 FROM `delivery_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `page_count_options` (`product_id`, `slug`, `label`, `page_count`, `base_rate_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`page_count`, `v`.`base_rate_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'both-sides' AS `slug`, 'Printed both sides' AS `label`, 2 AS `page_count`, 95 AS `base_rate_pence`, 'Full colour on the front and the back' AS `note`, 0 AS `sort_order`, true AS `is_active`) `v` WHERE `p`.`slug` = 'thank-you-cards' AND NOT EXISTS (SELECT 1 FROM `page_count_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `paper_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'silk-card' AS `slug`, 'Silk card' AS `label`, '1.0000' AS `multiplier`, '350gsm silk card — sturdy, with a soft sheen' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'gloss-card', 'Gloss card', '1.0000', '350gsm gloss card — bright, high-contrast photographs', 1, true UNION ALL SELECT 'uncoated-card', 'Uncoated card', '1.0500', '350gsm uncoated card — natural, and easy to write on', 2, true) `v` WHERE `p`.`slug` = 'thank-you-cards' AND NOT EXISTS (SELECT 1 FROM `paper_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `quantity_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `copies`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`copies`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT '10' AS `slug`, '10' AS `label`, '1.0000' AS `multiplier`, NULL AS `note`, 10 AS `copies`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT '25', '25', '0.9000', NULL, 25, 1, true UNION ALL SELECT '50', '50', '0.8000', NULL, 50, 2, true UNION ALL SELECT '75', '75', '0.7500', NULL, 75, 3, true UNION ALL SELECT '100', '100', '0.7000', NULL, 100, 4, true UNION ALL SELECT '150', '150', '0.6500', NULL, 150, 5, true UNION ALL SELECT '200', '200', '0.6000', NULL, 200, 6, true) `v` WHERE `p`.`slug` = 'thank-you-cards' AND NOT EXISTS (SELECT 1 FROM `quantity_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `delivery_options` (`product_id`, `slug`, `label`, `price_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`price_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'standard' AS `slug`, 'Standard delivery' AS `label`, 0 AS `price_pence`, 'Free — 3 to 5 working days' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'next-day', 'Next day delivery', 1000, 'Order before 11am for next working day', 1, true) `v` WHERE `p`.`slug` = 'thank-you-cards' AND NOT EXISTS (SELECT 1 FROM `delivery_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `page_count_options` (`product_id`, `slug`, `label`, `page_count`, `base_rate_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`page_count`, `v`.`base_rate_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'a4' AS `slug`, 'A4' AS `label`, 1 AS `page_count`, 1200 AS `base_rate_pence`, '210 × 297 mm — for a table or a frame' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'a3', 'A3', 1, 1800, '297 × 420 mm', 1, true UNION ALL SELECT 'a2', 'A2', 1, 2800, '420 × 594 mm', 2, true UNION ALL SELECT 'a1', 'A1', 1, 4000, '594 × 841 mm — the usual size for an easel', 3, true UNION ALL SELECT 'a0', 'A0', 1, 6000, '841 × 1189 mm', 4, true) `v` WHERE `p`.`slug` = 'memory-board' AND NOT EXISTS (SELECT 1 FROM `page_count_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `paper_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'print-only' AS `slug`, 'Print only' AS `label`, '1.0000' AS `multiplier`, 'Printed on 200gsm satin poster paper, to frame or pin up' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'mounted', 'Mounted on 5mm board', '1.6000', 'Mounted on rigid 5mm foam board, ready to stand on an easel or a table', 1, true UNION ALL SELECT 'mounted-easel', 'Mounted on 5mm board, with easel', '2.0000', 'Mounted on 5mm foam board and sent with a display easel', 2, true) `v` WHERE `p`.`slug` = 'memory-board' AND NOT EXISTS (SELECT 1 FROM `paper_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `quantity_options` (`product_id`, `slug`, `label`, `multiplier`, `note`, `copies`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`multiplier`, `v`.`note`, `v`.`copies`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT '1' AS `slug`, '1' AS `label`, '1.0000' AS `multiplier`, NULL AS `note`, 1 AS `copies`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT '2', '2', '1.0000', NULL, 2, 1, true UNION ALL SELECT '3', '3', '1.0000', NULL, 3, 2, true) `v` WHERE `p`.`slug` = 'memory-board' AND NOT EXISTS (SELECT 1 FROM `quantity_options` `o` WHERE `o`.`product_id` = `p`.`id`);--> statement-breakpoint
INSERT INTO `delivery_options` (`product_id`, `slug`, `label`, `price_pence`, `note`, `sort_order`, `is_active`) SELECT `p`.`id`, `v`.`slug`, `v`.`label`, `v`.`price_pence`, `v`.`note`, `v`.`sort_order`, `v`.`is_active` FROM `products` `p` JOIN (SELECT 'standard' AS `slug`, 'Standard delivery' AS `label`, 0 AS `price_pence`, 'Free — 3 to 5 working days' AS `note`, 0 AS `sort_order`, true AS `is_active` UNION ALL SELECT 'next-day', 'Next day delivery', 1000, 'Order before 11am for next working day', 1, true) `v` WHERE `p`.`slug` = 'memory-board' AND NOT EXISTS (SELECT 1 FROM `delivery_options` `o` WHERE `o`.`product_id` = `p`.`id`);
