import type { Metadata } from "next";
// Every font the site and the design editor use — the site's Newsreader /
// Work Sans pair and the editor's whole picker (FONT_OPTIONS in
// designEditor.ts) — self-hosted as --font-* variables. Loaded site-wide so
// /proof-render prints exactly what /design showed. Generated by
// scripts/vendor-fonts.ts; see there for why it isn't next/font/google.
import "../fonts/fonts.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "The Funeral Stationery | Order of Service booklets, printed and delivered",
  description:
    "Choose a design, add their photographs and words online, and we print on heavyweight paper and deliver anywhere in the UK. Order of Service booklets, memorial cards and more.",
  // favicon.ico comes from src/app/favicon.ico (file convention, wired automatically).
  icons: {
    icon: [
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en-GB" className="h-full antialiased">
      <body className="min-h-full flex flex-col bg-background text-on-surface font-body selection:bg-primary-container selection:text-on-primary-container">
        {children}
      </body>
    </html>
  );
}
